@extends('layouts.app')

@section('content')
<div class="container">
    <h3>Tambah Produk</h3>
    <form action="{{ route('products.store') }}" method="POST">
        @csrf

        <div class="mb-3">
            <label for="name" class="form-label">Nama Produk</label>
            <input type="text" name="name" id="name" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="brand_id">Brand</label>
            <select name="brand_id" id="brand_id" class="form-control" required>
                <option value="">-- Pilih Brand --</option>
                @foreach ($brands as $brand)
                    <option value="{{ $brand->id }}" data-name="{{ $brand->name }}">{{ $brand->name }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="type_id">Type</label>
            <select name="type_id" id="type_id" class="form-control" required>
                <option value="">-- Pilih Type --</option>
                @foreach($types as $type)
                    <option value="{{ $type->id }}" data-name="{{ $type->name }}">{{ $type->name }}</option>
                @endforeach
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Simpan</button>
        <a href="{{ route('products.index') }}" class="btn btn-secondary">Batal</a>
    </form>
</div>
@endsection

@push('scripts')
<script>
    const nameInput = document.getElementById('name');
    const brandSelect = document.getElementById('brand_id');
    const typeSelect = document.getElementById('type_id');

    let isAutoGenerated = true;

    // Deteksi jika nama diedit manual
    nameInput.addEventListener('input', () => {
        isAutoGenerated = false;
    });

    function updateProductName() {
        if (!isAutoGenerated) return;

        const brandText = brandSelect.options[brandSelect.selectedIndex]?.dataset.name || '';
        const typeText = typeSelect.options[typeSelect.selectedIndex]?.dataset.name || '';

        if (brandText || typeText) {
            nameInput.value = `${brandText} ${typeText}`.trim();
        }
    }

    brandSelect.addEventListener('change', () => {
        isAutoGenerated = true;
        updateProductName();
    });

    typeSelect.addEventListener('change', () => {
        isAutoGenerated = true;
        updateProductName();
    });
</script>
@endpush
